version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: x86
build:
  project: 3D Engine.sln
  parallel: true
  verbosity: normal
before_package:
- ps: Copy-Item E:\Repositorios\3D-Engine\$env:CONFIGURATION\3D Engine.exe E:\Repositorios\3D-Engine\Game\
artifacts:
- path: Game
  name: 3D-Engine
deploy:
- provider: GitHub
  auth_token: 2e215b3b2712eb9ec8e3fd518c48bfb639269d40
    secure: QhydgyQMxm8l8l9gAV7ByY9TCaj7XY0plvUrout15RVMfURdWPupt/Ra560eLxeO
  draft: false
  force_update: true
  on:
    CONFIGURATION: Release