version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: x86
build:
  project: 3D Engine.sln
  parallel: true
  verbosity: normal
before_package:
- ps: Copy-Item C:\projects\3D-game-engine\3D Engine\3D Engine.exe C:\projects\3D-game-engine\Game\
artifacts:
- path: Game
  name: 3D Engine
deploy:
- provider: GitHub
  auth_token:
    secure: QhydgyQMxm8l8l9gAV7ByY9TCaj7XY0plvUrout15RVMfURdWPupt/Ra560eLxeO
  draft: false
  force_update: true
  on:
    CONFIGURATION: Release
